// build.rs — Tauri build script for keylatch-app
//
// Responsibilities:
// 1. Run tauri_build::build() (required by Tauri).
// 2. Read packaging/redaction-patterns.json and generate
//    src/redaction_patterns.rs with REDACTION_PATTERNS const array.
//    This feeds both the Rust panic hook (FIND2-019 / S14-14) and the
//    tauri-plugin-log writer redaction wrapper.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Required by Tauri — must be called first.
    tauri_build::build();

    // Locate the redaction patterns JSON relative to the workspace root.
    // CARGO_MANIFEST_DIR is src-tauri/, so we go one level up.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let patterns_path = manifest_dir
        .parent()
        .expect("src-tauri must have a parent directory")
        .join("packaging")
        .join("redaction-patterns.json");

    // Invalidate the build if the patterns file changes.
    println!(
        "cargo:rerun-if-changed={}",
        patterns_path.display()
    );

    // Read and parse the JSON array of pattern strings.
    let json = fs::read_to_string(&patterns_path).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to read {}: {}",
            patterns_path.display(),
            e
        )
    });

    let patterns: Vec<String> = serde_json::from_str(&json).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to parse {}: {}",
            patterns_path.display(),
            e
        )
    });

    // Generate the Rust source file.
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("redaction_patterns.rs");

    let mut entries = Vec::new();
    for p in &patterns {
        // Escape the pattern for use in a Rust string literal.
        let escaped = p.replace('\\', "\\\\").replace('"', "\\\"");
        entries.push(format!("    \"{}\",", escaped));
    }

    let content = format!(
        "/// Auto-generated by build.rs from packaging/redaction-patterns.json.\n\
         /// FIND2-019 / S14-14: used by the panic hook and log writer to redact\n\
         /// credential prefixes before any output leaves the process.\n\
         pub const REDACTION_PATTERNS: &[&str] = &[\n\
         {}\n\
         ];\n",
        entries.join("\n")
    );

    fs::write(&out_path, content).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to write {}: {}",
            out_path.display(),
            e
        )
    });
}
