package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/keylatch/keylatch/internal/exitcode"
	"github.com/spf13/cobra"
)

// supportedIntegrationAgents is the canonical list of agents accepted by
// `keylatch init --integration <agent>`.
var supportedIntegrationAgents = []string{
	"claude-code",
	"gemini",
	"windsurf",
	"cursor",
	"generic",
}

// newInitIntegrationCmd returns the `keylatch init integration` subcommand.
// It detects the project language, writes a starter integration script, and
// writes .keylatch/integration.yml with detected agent and placeholder providers.
func newInitIntegrationCmd() *cobra.Command {
	var agentName string

	cmd := &cobra.Command{
		Use:   "integration",
		Short: "Scaffold a Keylatch integration for an AI agent",
		Long: `Scaffold a Keylatch integration for an AI agent in the current project.

Detects the project language (Go, Python, Node.js, Shell) and writes:
  - A starter integration script (scripts/keylatch-setup.sh, .py, or .ts)
  - .keylatch/integration.yml with the detected agent and placeholder providers

Supported agents: ` + strings.Join(supportedIntegrationAgents, ", ") + `

Examples:
  keylatch init integration --agent claude-code
  keylatch init integration --agent cursor
  keylatch init integration --agent generic`,
		RunE: func(c *cobra.Command, _ []string) error {
			if agentName == "" {
				return fmt.Errorf("--agent is required; supported: %s", strings.Join(supportedIntegrationAgents, ", "))
			}

			agentName = strings.ToLower(strings.TrimSpace(agentName))
			if !isValidIntegrationAgent(agentName) {
				return fmt.Errorf(
					"unknown agent %q\nSupported agents: %s",
					agentName, strings.Join(supportedIntegrationAgents, ", "),
				)
			}

			cwd, err := os.Getwd()
			if err != nil {
				fmt.Fprintf(c.ErrOrStderr(), "init integration: get cwd: %v\n", err)
				os.Exit(exitcode.OperationFailed)
				return nil
			}

			lang := detectProjectLanguage(cwd)

			if err := writeIntegrationConfig(c, cwd, agentName, lang); err != nil {
				fmt.Fprintf(c.ErrOrStderr(), "init integration: %v\n", err)
				os.Exit(exitcode.OperationFailed)
				return nil
			}

			if err := writeIntegrationScript(c, cwd, agentName, lang); err != nil {
				fmt.Fprintf(c.ErrOrStderr(), "init integration: %v\n", err)
				os.Exit(exitcode.OperationFailed)
				return nil
			}

			printIntegrationNextSteps(c, agentName, lang)
			return nil
		},
	}

	cmd.Flags().StringVar(&agentName, "agent", "", "AI agent to integrate with (required)")
	return cmd
}

// isValidIntegrationAgent reports whether name is in supportedIntegrationAgents.
func isValidIntegrationAgent(name string) bool {
	for _, a := range supportedIntegrationAgents {
		if a == name {
			return true
		}
	}
	return false
}

// projectLang identifies the primary language of a project.
type projectLang string

const (
	langGo     projectLang = "go"
	langPython projectLang = "python"
	langNode   projectLang = "node"
	langShell  projectLang = "shell"
)

// detectProjectLanguage probes cwd for well-known project files and returns
// the most specific match. Returns langShell if nothing is found.
func detectProjectLanguage(cwd string) projectLang {
	checks := []struct {
		file string
		lang projectLang
	}{
		{"go.mod", langGo},
		{"package.json", langNode},
		{"pyproject.toml", langPython},
		{"requirements.txt", langPython},
		{"setup.py", langPython},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(cwd, c.file)); err == nil {
			return c.lang
		}
	}
	return langShell
}

// integrationYMLTemplate is the .keylatch/integration.yml content.
const integrationYMLTemplate = `# .keylatch/integration.yml — generated by keylatch init integration
# Edit the providers list below to match your project's connections.
# Run 'keylatch connect <provider>' to store credentials for each provider.

agent: %s

# List the Keylatch connection names this project uses.
providers:
  - <your-provider>  # e.g. openrouter, openai, anthropic

# Integration guide: https://keylatch.dev/docs/integration/agents/%s.md
`

// writeIntegrationConfig writes .keylatch/integration.yml.
func writeIntegrationConfig(c *cobra.Command, cwd, agent string, _ projectLang) error {
	klDir := filepath.Join(cwd, ".keylatch")
	if err := os.MkdirAll(klDir, 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", klDir, err)
	}

	cfgPath := filepath.Join(klDir, "integration.yml")
	if _, err := os.Stat(cfgPath); err == nil {
		fmt.Fprintf(c.OutOrStdout(), "  .keylatch/integration.yml already exists — skipping\n")
		return nil
	}

	docSlug := agentDocSlug(agent)
	content := fmt.Sprintf(integrationYMLTemplate, agent, docSlug)
	if err := os.WriteFile(cfgPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}
	fmt.Fprintf(c.OutOrStdout(), "  Written: .keylatch/integration.yml\n")
	return nil
}

// agentDocSlug maps agent names to their doc URL slug.
func agentDocSlug(agent string) string {
	switch agent {
	case "claude-code":
		return "claude-code"
	case "gemini":
		return "gemini"
	case "windsurf":
		return "windsurf"
	case "cursor":
		return "cursor"
	default:
		return "generic"
	}
}

// integrationScriptTemplates maps project language to the starter script content.
// %s placeholders: provider name.
var integrationScriptSh = `#!/usr/bin/env bash
# scripts/keylatch-setup.sh — generated by keylatch init integration
# Run this script to set up Keylatch for this project.
# Edit <your-provider> with your actual provider name.
set -euo pipefail

PROVIDER="<your-provider>"  # e.g. openrouter

# 1. Bootstrap Keylatch (idempotent)
keylatch bootstrap --backend=file

# 2. Connect provider credential (interactive prompt)
echo "Connecting provider: ${PROVIDER}"
keylatch connect "${PROVIDER}"

# 3. Start the local gateway in the background
keylatch gateway up --detach

# 4. Verify
keylatch doctor
echo "Setup complete. Run your script with:"
echo "  keylatch run --clean-env ${PROVIDER} -- <your-command>"
`

var integrationScriptPy = `#!/usr/bin/env python3
"""
scripts/keylatch_setup.py — generated by keylatch init integration
Run this script to set up Keylatch for this project.
Edit PROVIDER with your actual provider name.
"""
import subprocess
import sys

PROVIDER = "<your-provider>"  # e.g. openrouter


def run(cmd: list[str]) -> None:
    result = subprocess.run(cmd, check=True)
    _ = result


def main() -> None:
    # 1. Bootstrap Keylatch (idempotent)
    run(["keylatch", "bootstrap", "--backend=file"])

    # 2. Connect provider credential (interactive prompt)
    print(f"Connecting provider: {PROVIDER}")
    run(["keylatch", "connect", PROVIDER])

    # 3. Start the local gateway in the background
    run(["keylatch", "gateway", "up", "--detach"])

    # 4. Verify
    run(["keylatch", "doctor"])

    print(f"\nSetup complete. Run your script with:")
    print(f"  keylatch run --clean-env {PROVIDER} -- python3 your_script.py")


if __name__ == "__main__":
    main()
`

// integrationScriptTS is built via string concatenation because raw string
// literals (backtick-delimited) cannot contain backtick characters, which are
// used as TypeScript template-literal delimiters.
var integrationScriptTS = "#!/usr/bin/env npx tsx\n" +
	"/**\n" +
	" * scripts/keylatchSetup.ts — generated by keylatch init integration\n" +
	" * Run: npx tsx scripts/keylatchSetup.ts\n" +
	" * Edit PROVIDER with your actual provider name.\n" +
	" */\n" +
	"import { execSync } from 'node:child_process';\n" +
	"\n" +
	"const PROVIDER = '<your-provider>'; // e.g. openrouter\n" +
	"\n" +
	"function run(cmd: string): void {\n" +
	"  execSync(cmd, { stdio: 'inherit' });\n" +
	"}\n" +
	"\n" +
	"// 1. Bootstrap Keylatch (idempotent)\n" +
	"run('keylatch bootstrap --backend=file');\n" +
	"\n" +
	"// 2. Connect provider credential (interactive prompt)\n" +
	"console.log(`Connecting provider: ${PROVIDER}`);\n" +
	"run(`keylatch connect ${PROVIDER}`);\n" +
	"\n" +
	"// 3. Start the local gateway in the background\n" +
	"run('keylatch gateway up --detach');\n" +
	"\n" +
	"// 4. Verify\n" +
	"run('keylatch doctor');\n" +
	"\n" +
	"console.log(`\\nSetup complete. Run your script with:`);\n" +
	"console.log(`  keylatch run --clean-env ${PROVIDER} -- npx tsx your_script.ts`);\n"

// writeIntegrationScript writes the language-appropriate starter script.
func writeIntegrationScript(c *cobra.Command, cwd, agent string, lang projectLang) error {
	// agent is currently unused — script variant is language-driven only.
	_ = agent
	scriptsDir := filepath.Join(cwd, "scripts")
	if err := os.MkdirAll(scriptsDir, 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", scriptsDir, err)
	}

	var filename, content string
	var mode os.FileMode

	switch lang {
	case langPython:
		filename = "keylatch_setup.py"
		content = integrationScriptPy
		mode = 0o755
	case langNode:
		filename = "keylatchSetup.ts"
		content = integrationScriptTS
		mode = 0o644
	default: // go, shell, unknown
		filename = "keylatch-setup.sh"
		content = integrationScriptSh
		mode = 0o755
	}

	scriptPath := filepath.Join(scriptsDir, filename)
	if _, err := os.Stat(scriptPath); err == nil {
		fmt.Fprintf(c.OutOrStdout(), "  scripts/%s already exists — skipping\n", filename)
		return nil
	}

	if err := os.WriteFile(scriptPath, []byte(content), mode); err != nil {
		return fmt.Errorf("write %s: %w", scriptPath, err)
	}
	fmt.Fprintf(c.OutOrStdout(), "  Written: scripts/%s\n", filename)
	return nil
}

// printIntegrationNextSteps prints the "next steps" guidance for the user.
func printIntegrationNextSteps(c *cobra.Command, agent string, lang projectLang) {
	w := c.OutOrStdout()
	docSlug := agentDocSlug(agent)

	var scriptCmd string
	switch lang {
	case langPython:
		scriptCmd = "python3 scripts/keylatch_setup.py"
	case langNode:
		scriptCmd = "npx tsx scripts/keylatchSetup.ts"
	default:
		scriptCmd = "bash scripts/keylatch-setup.sh"
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "Next steps:\n")
	fmt.Fprintf(w, "  1. Edit .keylatch/integration.yml — replace <your-provider> with your provider name\n")
	fmt.Fprintf(w, "  2. Run: %s\n", scriptCmd)
	fmt.Fprintf(w, "  3. Integration guide: https://keylatch.dev/docs/integration/agents/%s.md\n", docSlug)
	fmt.Fprintln(w)
}
