package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/keylatch/keylatch/internal/exitcode"
	"github.com/keylatch/keylatch/internal/llmcontext"
	"github.com/spf13/cobra"
)

// keylatchYAMLSkeleton is the comment-annotated keylatch.yaml skeleton written
// by `keylatch init --ci`.
const keylatchYAMLSkeleton = `# keylatch.yaml — generated by keylatch init --ci
# Edit the fields below then run: keylatch bootstrap --backend=<backend>

# Backend: file | keychain (macOS) | op | bw
backend: file

# Default namespace for connections.
default_namespace: default

# Audit log settings.
audit:
  enabled: true
  max_size_bytes: 5242880  # 5 MiB

# UI server settings (local only).
ui:
  bind: 127.0.0.1
`

// githubActionsSnippet is the GitHub Actions workflow printed by `keylatch init --ci`.
const githubActionsSnippet = `name: keylatch-ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  keylatch-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install keylatch
        run: |
          curl -sSfL https://keylatch.dev/install.sh | sh

      - name: Bootstrap keylatch
        run: keylatch setup --non-interactive --backend=file

      - name: Doctor check
        run: keylatch doctor
`

// githubActionsWorkflowPath is the path written when --write is passed.
const githubActionsWorkflowPath = ".github/workflows/keylatch-ci.yml"

// newInitCmd returns the `keylatch init` command with a `--ci` submode.
// §2.4: generates keylatch.yaml skeleton and optional GitHub Actions snippet.
func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a keylatch configuration skeleton",
		Long: `init generates a keylatch.yaml skeleton suitable for CI or a new project.

With --ci:
  - Writes keylatch.yaml with comment-annotated defaults (idempotent)
  - Prints a GitHub Actions snippet, or writes it with --write
  - Completes in under 30 seconds

Exit codes:
  0  success
  1  user error (path conflict, unwritable directory)
  5  operation failed`,
	}

	cmd.AddCommand(newInitCICmd())
	cmd.AddCommand(newInitIntegrationCmd())
	return cmd
}

// newInitCICmd returns the `keylatch init --ci` subcommand.
func newInitCICmd() *cobra.Command {
	var write bool
	var configOut string

	cmd := &cobra.Command{
		Use:   "ci",
		Short: "Generate CI configuration skeleton and GitHub Actions workflow snippet",
		Long: `Generate a keylatch.yaml skeleton and GitHub Actions workflow snippet for CI.

This command is idempotent — safe to re-run. It will not overwrite an existing
keylatch.yaml unless --force is passed.

With --write, it writes the GitHub Actions snippet to:
  .github/workflows/keylatch-ci.yml

Exit codes:
  0  success
  1  user error (path conflict, unwritable file)
  5  operation failed`,
		RunE: func(c *cobra.Command, _ []string) error {
			env := llmcontext.DefaultLookup

			// Resolve config output path.
			target := configOut
			if target == "" {
				// Default: keylatch.yaml in the current working directory.
				cwd, err := os.Getwd()
				if err != nil {
					fmt.Fprintf(c.ErrOrStderr(), "init ci: get cwd: %v\n", err)
					os.Exit(exitcode.OperationFailed)
					return nil
				}
				target = filepath.Join(cwd, "keylatch.yaml")
			}

			// Check idempotency: do not overwrite existing config unless --force.
			force, _ := c.Flags().GetBool("force")
			if !force {
				if _, err := os.Stat(target); err == nil {
					fmt.Fprintf(c.OutOrStdout(), "  keylatch.yaml already exists at %s — skipping (pass --force to overwrite)\n", target)
				} else {
					// Write the skeleton.
					if err := os.WriteFile(target, []byte(keylatchYAMLSkeleton), 0o600); err != nil {
						fmt.Fprintf(c.ErrOrStderr(), "init ci: write %s: %v\n", target, err)
						os.Exit(exitcode.OperationFailed)
						return nil
					}
					fmt.Fprintf(c.OutOrStdout(), "  Written: %s\n", target)
				}
			} else {
				if err := os.WriteFile(target, []byte(keylatchYAMLSkeleton), 0o600); err != nil {
					fmt.Fprintf(c.ErrOrStderr(), "init ci: write %s: %v\n", target, err)
					os.Exit(exitcode.OperationFailed)
					return nil
				}
				fmt.Fprintf(c.OutOrStdout(), "  Written: %s\n", target)
			}

			// Emit or write GitHub Actions snippet.
			if write {
				cwd, err := os.Getwd()
				if err != nil {
					fmt.Fprintf(c.ErrOrStderr(), "init ci: get cwd: %v\n", err)
					os.Exit(exitcode.OperationFailed)
					return nil
				}
				wfPath := filepath.Join(cwd, githubActionsWorkflowPath)
				wfDir := filepath.Dir(wfPath)
				if err := os.MkdirAll(wfDir, 0o750); err != nil {
					fmt.Fprintf(c.ErrOrStderr(), "init ci: mkdir %s: %v\n", wfDir, err)
					os.Exit(exitcode.OperationFailed)
					return nil
				}
				if _, statErr := os.Stat(wfPath); statErr == nil && !force {
					fmt.Fprintf(c.OutOrStdout(), "  %s already exists — skipping (pass --force to overwrite)\n", wfPath)
				} else {
					if err := os.WriteFile(wfPath, []byte(githubActionsSnippet), 0o600); err != nil {
						fmt.Fprintf(c.ErrOrStderr(), "init ci: write %s: %v\n", wfPath, err)
						os.Exit(exitcode.OperationFailed)
						return nil
					}
					fmt.Fprintf(c.OutOrStdout(), "  Written: %s\n", wfPath)
				}
			} else {
				// Print snippet to stdout (with a comment header).
				fmt.Fprintln(c.OutOrStdout())
				fmt.Fprintln(c.OutOrStdout(), "GitHub Actions snippet (pass --write to save to "+githubActionsWorkflowPath+"):")
				fmt.Fprintln(c.OutOrStdout())
				// Indent the snippet for readability.
				for _, line := range strings.Split(githubActionsSnippet, "\n") {
					fmt.Fprintf(c.OutOrStdout(), "  %s\n", line)
				}
			}

			// Print the "get started" line (§2.6 first-run stdout hint).
			fmt.Fprintln(c.OutOrStdout(), "Get started: keylatch.dev/start")

			_ = env
			return nil
		},
	}

	cmd.Flags().BoolVar(&write, "write", false, "write GitHub Actions snippet to "+githubActionsWorkflowPath)
	cmd.Flags().StringVar(&configOut, "config", "", "output path for keylatch.yaml (default: ./keylatch.yaml)")
	cmd.Flags().Bool("force", false, "overwrite existing files")
	return cmd
}
