# Homebrew formula for keylatch — stub.
#
# This file is a placeholder for users who want to tap the repository
# directly (`brew install --HEAD keylatch/keylatch/keylatch`). The
# authoritative formula at each release is auto-generated by goreleaser
# and published to `keylatch/homebrew-tap` (see .goreleaser.yml `brews`
# stanza). The auto-generated formula contains correct SHA-256 hashes
# for each platform tarball; the values below are TODO placeholders to
# be filled in at the first tagged release.
#
# To install the released version, prefer the official tap:
#   brew tap keylatch/tap
#   brew install keylatch
class Keylatch < Formula
  desc "Zero-trust credential vault CLI for AI-assisted workflows"
  homepage "https://github.com/keylatch/keylatch"
  license "Apache-2.0"
  version "0.9.2"

  # Release tarball URLs. The goreleaser archive name template is
  # `{{.ProjectName}}_{{.Os}}_{{.Arch}}.tar.gz` by default; sha256 hashes
  # are computed by goreleaser at release time and written to
  # SHA256SUMS in the release artifacts.
  on_macos do
    on_arm do
      url "https://github.com/keylatch/keylatch/releases/download/v#{version}/keylatch_Darwin_arm64.tar.gz"
      sha256 "TODO_FILL_AT_FIRST_RELEASE"
    end
    on_intel do
      url "https://github.com/keylatch/keylatch/releases/download/v#{version}/keylatch_Darwin_amd64.tar.gz"
      sha256 "TODO_FILL_AT_FIRST_RELEASE"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/keylatch/keylatch/releases/download/v#{version}/keylatch_Linux_arm64.tar.gz"
      sha256 "TODO_FILL_AT_FIRST_RELEASE"
    end
    on_intel do
      url "https://github.com/keylatch/keylatch/releases/download/v#{version}/keylatch_Linux_amd64.tar.gz"
      sha256 "TODO_FILL_AT_FIRST_RELEASE"
    end
  end

  def install
    bin.install "keylatch"

    # Shell completions are generated by the binary itself.
    generate_completions_from_executable(bin/"keylatch", "completion")
  end

  test do
    # Smoke test: `keylatch --version` should print the formula version.
    output = shell_output("#{bin}/keylatch --version")
    assert_match version.to_s, output
  end

  def caveats
    <<~EOS
      To complete installation, run:
        keylatch setup

      This will configure your credential backend, connect your first provider,
      and optionally start the Keylatch gateway daemon.

      Documentation: https://docs.keylatch.io
    EOS
  end
end
