package completion

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

func generateBash(root *cobra.Command) (string, error) {
	var sb strings.Builder
	name := root.Name()
	subs := subcommandNames(root)

	fmt.Fprintf(&sb, "# keylatch bash completion — generated by `keylatch completion bash`\n")
	fmt.Fprintf(&sb, "# Add to your ~/.bashrc: source <(keylatch completion bash)\n\n")

	fmt.Fprintf(&sb, "_%s_completions() {\n", name)
	fmt.Fprintf(&sb, " local cur\n")
	fmt.Fprintf(&sb, " cur=\"${COMP_WORDS[COMP_CWORD]}\"\n\n")

	if len(subs) > 0 {
		fmt.Fprintf(&sb, " local subcommands='%s'\n", strings.Join(subs, " "))
		fmt.Fprintf(&sb, " COMPREPLY=($(compgen -W \"$subcommands\" -- \"$cur\"))\n")
	}

	fmt.Fprintf(&sb, "}\n\n")
	fmt.Fprintf(&sb, "complete -F _%s_completions %s\n", name, name)

	return sb.String(), nil
}
