package completion

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func generateFish(root *cobra.Command) (string, error) {
	var sb strings.Builder
	name := root.Name()

	fmt.Fprintf(&sb, "# keylatch fish completion — generated by `keylatch completion fish`\n")
	fmt.Fprintf(&sb, "# Place in ~/.config/fish/completions/%s.fish\n\n", name)

	// Root persistent flags.
	root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		desc := strings.ReplaceAll(f.Usage, "'", "\\'")
		if f.Shorthand != "" {
			fmt.Fprintf(&sb, "complete -c %s -s %s -l %s -d '%s'\n",
				name, f.Shorthand, f.Name, desc)
		} else {
			fmt.Fprintf(&sb, "complete -c %s -l %s -d '%s'\n", name, f.Name, desc)
		}
	})

	// Subcommands.
	for _, sub := range root.Commands() {
		if sub.Hidden {
			continue
		}
		subName := sub.Name()
		desc := strings.ReplaceAll(sub.Short, "'", "\\'")
		fmt.Fprintf(&sb, "complete -c %s -n '__fish_use_subcommand' -f -a %s -d '%s'\n",
			name, subName, desc)

		// Subcommand flags.
		sub.Flags().VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			flagDesc := strings.ReplaceAll(f.Usage, "'", "\\'")
			cond := fmt.Sprintf("__fish_seen_subcommand_from %s", subName)
			if f.Shorthand != "" {
				fmt.Fprintf(&sb, "complete -c %s -n '%s' -s %s -l %s -d '%s'\n",
					name, cond, f.Shorthand, f.Name, flagDesc)
			} else {
				fmt.Fprintf(&sb, "complete -c %s -n '%s' -l %s -d '%s'\n",
					name, cond, f.Name, flagDesc)
			}
		})
	}

	return sb.String(), nil
}
